### ISSUE TITLE
Remove hard-coded salt in password.rs

### ISSUE THREAD

**Issue by cmosetick** [ashuio/shavee#23]
On line 4 of `password.rs` in shavee-core consider replacing the hard-coded salt with a user configurable build time or environment variable that can be used for the salt parameter.

 - Consider throwing an error if salt is not defined by the user themselves.

https://github.com/ashuio/shavee/blob/f107b3cc60c5e24438cfa51edec3b9cfe9070be5/shavee-core/src/password.rs#L4

**Comment by kiavash-at-work** [comment]
Technically implementing a user configurable salt either by environment variables or compile configuration is not complex and can be done easily, however I would like to bring your attention to [this](https://github.com/ashuio/shavee/commit/ebf3fcd40970155e408d14f3308bf57e508fbe5a#r54798078) code review discussion regarding the same topic.

**Comment by kiavash-at-work** [comment]
Hi @ashuio,

I am wondering how you like to proceed with this request? As you recall we had previously discussed it in the code review mentioned above.

Thanks,

**Comment by ashuio** [comment]
Hey @kiavash-at-work , so I was thinking maybe we can ket the user configure the salt somewhere and fallback to this one if none are passed. Maybe a command line argument.

**Comment by kiavash-at-work** [comment]
That would be an easy change. Would that meet your target @cmosetick ?

For example, to implement @ashuio suggestion, [this line](https://github.com/ashuio/shavee/blob/737775d4889084a53f9c05d29be1e8404b6c82e6/shavee-core/src/password.rs#L4) can be changed to 

``` rust
    const STATIC_SALT: &str = "This Project is Dedicated to Aveesha.";
    // If SHAVEE_SALT environment variable exists, then use its value,
    // Otherwise the use the static for salt
    let env_salt = env::var("SHAVEE_SALT").unwrap_or(String::from(STATIC_SALT));
    let salt = env_salt.as_bytes();
```

If so, if the `SHAVEE_SALT` is defined in the ENV then it will be used otherwise the default static salt will be used.

**Comment by ashuio** [comment]
That would work however i am skeptical about the security implications of storing a salt in an environment variable.

**Comment by kupiakos** [comment]
@kiavash-at-work brought this to my attention. Let me try to clear some things up:

- Salts exist to thwart pre-computed dictionary attacks by making the same input hash differently for different users. A static salt is nearly entirely useless, as you can generate a rainbow table that targets all users of this static salt. I'd argue it's worse than no salt at all, as it provides a false sense of security that "the hash is salted". This is a common security vulnerability, described in [CWE-760](https://cwe.mitre.org/data/definitions/760.html).
- Salts are [not secret](https://stackoverflow.com/questions/213380/the-necessity-of-hiding-the-salt-for-a-hash). They should be stored in cleartext next to the data that needs the salt. In a password database, this is next to the password hash. There is no risk storing a salt in an environment variable. If there is a risk, your system is not using salts as they are intended to be used.
- Different ZFS filesystems should have different salts for the password. This means that a user configurable build time variable is the wrong way to go about it: the compiled binary would only be able to access one filesystem.

So, this is what I see as the way forward:
- When creating a filesystem, generate a random salt and store it alongside the filesystem. A [ZFS User Property](https://docs.oracle.com/cd/E19253-01/819-5461/gdrcw/index.html) would be a good way to do this, as it ensures the data that needs decrypting and the salt necessary to decrypt it are next to each other. This is assuming you can access these properties before decryption; I don't know ZFS very well.
- When loading a filesystem, perform a backwards compatible salt detection:
  1. If the `SHAVEE_SALT` environment variable is defined, use this as the salt.
  2. Otherwise, check the ZFS User Properties to find the salt.
  3. If it cannot be found in a user property, fall back to the old `STATIC_SALT` defined here, to allow for backwards compatibility. Print a warning that the user should regenerate the password, which will give it a random salt. Or, do this regeneration automatically if reasonable.
- The `SHAVEE_SALT` environment variable can also be used during password generation to specify a specific salt. New filesystems should never use the static salt.
- Consider publishing a security bulletin for users indicating they should do this migration to a random salt.

**Comment by ashuio** [comment]
Hey @kupiakos,

First of all thank you for sharing your expertise and i woukd say i agree with what you've proposed, ZFS user properties seems like a good idea and i will look into it, we should move away from static salts.

**Comment by ashuio** [comment]
So we can indeed use ZFS user properties like @kupiakos suggested, they are exposed even when encryption key is not loaded, they support upto 256 characters so we can have a sufficiently long salt.

**Comment by ashuio** [comment]
@kiavash-at-work what you've suggested is exactly what's suggested in the official zfs docs too and that indeed woukd be best practice.

**Comment by ashuio** [comment]
@kiavash-at-work I think we can use a property to store the unlock method too eg Yubikey When we create a new dataset. PAM module can use it for multi user support since you wont need to mention it as a argument and you won't have to specify it in cli while using it manually too.

**Comment by kiavash-at-work** [comment]
> use a property to store the unlock method too

Fantastic idea. I suggest to add it to TODO list #20 and come back to implement it later.

**Comment by kupiakos** [comment]
You're welcome for the expertise, always happy to improve security 😌

> they support upto 256 characters so we can have a sufficiently long salt.

For reference, NIST recommends
[128 bits](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-132.pdf) as a safe minimum salt length. So, 16 bytes/characters is a sufficient salt length so long as it is cryptographically random.

> we can indeed use ZFS user properties like @kupiakos suggested

It was @kiavash-at-work who suggested ZFS user properties to me when we discussed the system requirements for the salt. Don't want to take undue credit. 😉 Glad to hear that suggestion could simplify other parts of the design!

**Comment by kiavash-at-work** [comment]
I will try to submit a PR (once all the unit tests pass!) with the following algorithm based on the discussion on issue #23; to determine which salt to use:
1. Check if the ZFS dataset is specified
2. Check if the ZFS dataset has salt property value `com.github.shavee:salt` then use it
3. If salt is not extracted from (2), then check for the salt environment variable `SHAVEE_SALT`
4. If the salt environment variable exists, use it
5. If none of the above is valid, then use the default static salt.

However to simplify the code:
1. Generate a variable to store the salt environment variable `SHAVEE_SALT` or static salt if the environment variable is not set;
2. If the ZFS dataset has salt property value `com.github.shavee:salt` use it, otherwise use salt from (1)

``` rust
// Static salt for backward compatibility
pub const STATIC_SALT: &str = "This Project is Dedicated to Aveesha.";

// ZFS property used to store the random salt
pub const ZFS_PROPERTY_SALT: &str = "com.github.shavee:salt";

// Name of Shell Environment variable for storing salt
pub const ENV_SALT_VARIABLE: &str = "SHAVEE_SALT";

// for maximum compatibility limit the random character to ASCII alphabets
pub const SALT_CHARSET: &str = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

// Len of the random salt (in Bytes)
pub const RANDOM_SALT_LEN: usize = 32;

pub fn get_salt(dataset: Option<Dataset>) -> Result<Vec<u8>, Box<dyn Error>> {
    // Generate salt to be either env variable or default static.
    let store_env_salt = std::env::var(crate::ENV_SALT_VARIABLE);
    let env_or_static_salt = store_env_salt
        .as_deref()
        .unwrap_or(crate::STATIC_SALT)
        .as_bytes()
        .to_vec();

    // If ZFS dataset has salt value use it, otherwise use the salt from above
    let salt = match dataset {
        Some(dataset) => {
            match dataset.get_property(crate::ZFS_PROPERTY_SALT.to_owned())? {
                Some(property_value) => property_value.as_bytes().to_vec(),
                // ZFS salt property is empty use the next
                None => env_or_static_salt,
            }
        }
        // if no dataset is specified, then check for environment variable
        None => env_or_static_salt,
    };
    Ok(salt)
}
```

Also a separate function to generate a random (32byte) salt and store it in `com.github.shavee:salt`

```rust
// If there is a ZFS dataset then the salt will be stored in the dataset property
// Otherwise it checks for the ENV salt variable, and uses it if it exists
// If none of the above exists then uses the default static salt
pub fn generate_salt(dataset: Option<Dataset>) -> Result<Vec<u8>, Box<dyn Error>> {
    let generated_salt = match dataset {
        // ZFS dataset is knownm generate random salt and store it in the property.
        Some(dataset) => {
            // Generate a randon salt
            let random_salt = random_string::generate(crate::RANDOM_SALT_LEN, crate::SALT_CHARSET);
            // Store it in the ZFS dataset property. Exit on error
            dataset.set_property(crate::ZFS_PROPERTY_SALT.to_owned(), &random_salt)?;
            // Return the generated salt
            random_salt.into()
        }
        // No ZFS dataset, use the ENV valiable if exists otherwise use default static salt
        None => {
            let store_env_salt = std::env::var(crate::ENV_SALT_VARIABLE);
            let env_or_static_salt = store_env_salt
                .as_deref()
                .unwrap_or(crate::STATIC_SALT)
                .as_bytes()
                .to_vec();
            env_or_static_salt
        }
    };
    Ok(generated_salt)
}
```

**Comment by kupiakos** [comment]
Some major issues with that proposed design:

- Do NOT use `random_string` for cryptography! 😵  It [explicitly](https://github.com/DmitrijVC/random-string/blob/master/src/generator.rs#L32) [uses](https://docs.rs/fastrand/latest/fastrand/index.html) a random generator that is not cryptographically secure. This is another [well-known security vulnerability](https://cwe.mitre.org/data/definitions/338.html). Instead use something like [`rang::rngs::StdRng`](https://rust-random.github.io/rand/rand/rngs/struct.StdRng.html) or some other system that explicitly labels itself as cryptographically secure.
- Do not restrict the character set for the salt. It must be cryptographically random and have at least 128 bits of entropy. Restricting the character set requires a much longer salt than is necessary. What compatibility are you worried about? If it might affect some external tool, base64 the salt when storing/retrieving.
 - Keep the actual salt passed to the password hasher represented as a `&[u8]`; it is **not** a string, but rather binary data. ZFS user properties can store arbitrary binary data.

**Comment by kiavash-at-work** [comment]
Thanks for reviewing and providing suggestions.

- [ ] use `rang::rngs` instead of `random_string` to generate a `[u8]` (~string~) salt
- [ ] Base64 encode/decode to store generated salt in ZFS property (to avoid any potential tools compatibility)

```rust
/// If there is a ZFS dataset then the salt will be stored in the dataset property
/// Otherwise it checks for the ENV salt variable, and uses it if it exists
/// If none of the above exists then uses the default static salt
pub fn generate_salt(dataset: Option<Dataset>) -> Result<Vec<u8>, Box<dyn Error>> {
    let generated_salt = match dataset {
        // ZFS dataset is knownm generate random salt and store it in the property.
        Some(dataset) => {
            // Generate a randon salt usig OS randomness
            let mut random_salt = [0u8; crate::RANDOM_SALT_LEN];
            rand::rngs::OsRng.fill_bytes(&mut random_salt);
            // Store it in the ZFS dataset property and store it as base64. Exit on error
            dataset.set_property(
                crate::ZFS_PROPERTY_SALT.to_owned(),
                &base64::encode(&random_salt),
            )?;
            // Return the generated salt
            random_salt.into()
        }
        // No ZFS dataset, use the ENV valiable if exists otherwise use default static salt
        None => {
            let store_env_salt = std::env::var(crate::ENV_SALT_VARIABLE);
            let env_or_static_salt = store_env_salt
                .as_deref()
                .unwrap_or(crate::STATIC_SALT)
                .as_bytes()
                .to_vec();
            env_or_static_salt
        }
    };
    Ok(generated_salt)
}
```

**Comment by ashuio** [comment]
Hey @kupiakos, can you help us out with one more thing?

We are currently using SHA512 to hash the passwords, how many rounds of that would you recommend ?

**Comment by kupiakos** [comment]
@ashuio 

A) Do not use SHA-512 to hash passwords. It is a hash with [insufficient computational effort for passwords](https://cwe.mitre.org/data/definitions/916.html). Multiple rounds does not solve this. We're at about 2.5 billion SHA-512 hashes/sec on a single video card and it's only going to get faster as ASICs and video cards improve.

B) It appears that shavee _doesn't_ use SHA-512 for passwords, [it uses argon2](https://github.com/ashuio/shavee/blob/master/shavee-core/src/password.rs#L17) as of ebf3fcd. Here's what I think of that function specifically:
  - The static salt is an issue, and that's being resolved here.
  - `password: &[u8]` is more idiomatic for the parameter than `Vec<u8>`.
  - I've checked up that the `secret` field isn't required to have contents to uphold security, it's truly optional. If you want you can put that `secret` field as the `password` and then use the literal password provided.
  - I'm a little concerned that the `time_cost` is set as `1`; the [default is `3`](https://docs.rs/rust-argon2/latest/src/argon2/common.rs.html#43). I don't see any explanation for the config choices in the [original commit](https://github.com/ashuio/shavee/commit/ebf3fcd40970155e408d14f3308bf57e508fbe5a). Consider replacing the config with `Config::default()` and only override specific configs you know need to be changed.

C) A nit for @kiavash-at-work. You don't need to create an array and then copy it to a vector, you can put the hash directly into the vector:

```rust
        Some(dataset) => {
            // Generate a random salt using OS randomness
            let mut random_salt = vec![0u8; crate::RANDOM_SALT_LEN];
            rand::rngs::OsRng.fill_bytes(&mut random_salt);
            // Store it in the ZFS dataset property and store it as base64. Exit on error
            dataset.set_property(
                crate::ZFS_PROPERTY_SALT.to_owned(),
                &base64::encode(&random_salt),
            )?;
            // Return the generated salt
            random_salt
        }
```

**Comment by kiavash-at-work** [comment]
> that the time_cost is set as 1; the [default is 3](https://docs.rs/rust-argon2/latest/src/argon2/common.rs.html#43). I don't see any explanation for the config choices in the [original commit](https://github.com/ashuio/shavee/commit/ebf3fcd40970155e408d14f3308bf57e508fbe5a). Consider replacing the config with Config::default() and only override specific configs you know need to be changed

I totally agree with this suggestion however because it will change the result of `argon2` hash function, it will need a migration strategy for the current datasets.

**Comment by ashuio** [comment]
If we are gonna break backwards compatibility we might aswell remove the static salt and possibly make all other breaking changes.

As suggested by @kiavash-at-work we can have a warning and upgrade instructions for users using 0.5.x and lower.

**Comment by ashuio** [comment]
After some testing, I think we should keep the argon config as is.

Increasing the time requirements drastically increases the time a user has to wait at login screen after password entry and having multiple datasets increases it even more.

I think it's a trade-off for UX we can make.
@kiavash-at-work thoughts?

**Comment by kiavash-at-work** [comment]
From a user experience perspective, it may be acceptable to break the backward compatibility between major releases assuming there is an auxiliary code that helps a user to upgrade its datasets.

**Comment by ashuio** [comment]
@kiavash-at-work Yes, it is worth it but the problem I am facing with using RFC9106 is that it takes too much time per dataset to derive they key and thus the user has to wait a long time on the login screen.

**Comment by kiavash-at-work** [comment]
> t takes too much time per dataset to derive they key

I would like to suggest looking into the value added of the proposal and potentially look into quantitative measurements or comparison data sets to assess its pro/cons.

**Comment by cmosetick** [comment]
Regarding the discussion around breaking backward compatibility, I'd speculate that most users are willing to accept this for a < 1.0 project.

After 1.0 opinions change.

**Comment by ashuio** [comment]
So after some basic testing it seems the RFC9106 config takes approx. `2.7s` PER dataset vs the `0.07s` with our config

The RFC Config
```
 pub fn rfc9106() -> Config<'a> {
        Config {
            ad: &[],
            hash_length: 32,
            lanes: 1,
            mem_cost: 2097152,
            secret: &[],
            time_cost: 1,
            variant: Variant::Argon2id,
            version: Version::Version13,
        }
    }
```

While our config is 
```
let config = Config {
        variant: Variant::Argon2id,
        version: Version::Version13,
        mem_cost: 65536,
        time_cost: 1,
        lanes: 4,
        secret: &[],
        ad: &[],
        hash_length: 64,
    };
```

The only difference seems to be the memory cost

Keeping in my mind that a user might have multiple datasets to unlock at login the time adds up.
e.g. to unlock 4 datasets on login a user will have to wait over 10s on login screen.

Any inputs regarding this are welcome

**Comment by kiavash-at-work** [comment]
> replacing sha512

LGTM, but maybe for the major release 1.0 that will brake the backward compatibility.

**Comment by ashuio** [comment]
Yes that's the plan, I wanna make all the breaking changes in a single release so users don't have to migrate everytime.

I think a guide on upgrading will also be useful for old users.

**Comment by ashuio** [comment]
I have created a new branch with the proposed changes

**Comment by kupiakos** [comment]
It appears that the `lanes` parameter has to do with parallelism: by changing it from 4 to 1, that's eliminated any performance advantage that a multi-core system could provide. I suggest redoing the performance timing with the `lanes` parameter of `Config` either set to 4 as it was before, or set to [`std::thread::available_parallelism`](https://doc.rust-lang.org/std/thread/fn.available_parallelism.html).

@ashuio I'm guessing you came up with that config from the `FIRST RECOMMENDED option` in [the RFC](https://datatracker.ietf.org/doc/rfc9106/)? How did you come to the config suggested in https://github.com/ashuio/shavee/issues/23#issuecomment-1838846572? Did you follow its recommended procedure for selecting the type and parameters for practical use, and if so, can you show your work? Its section on parameter choice does mention key derivation for hard drive encryption specifically:

>   Key derivation for hard-drive encryption, which takes 3 seconds on
      a 2 GHz CPU using 2 cores -- Argon2id with 4 lanes and 6 GiB of
      RAM.

On a faster machine with a better `lanes` parameter, you should see more performant results. It's normal for it to take a second or two to derive the key for hard drive encryption: that time specifically makes it harder for attackers to brute force or intelligently guess many passwords. Considering it should just be for login from boot and not for unlocking, this seems like a perfectly fine price to pay for security.

**Comment by ashuio** [comment]
Hi @kupiakos , thank you for looking into this.

IMO we can't use `std::thread::available_parellelism` cannot be used by us because the number of threads actually changes the final hash, it'll be perfectly usable on a single system but if the pool is migrated to another system the key derivation maybe different depending on the resources available on the new system. keeping it static makes it so a user can derive the key on any system regardless. I However do agree that we should change it back to 4 like before.

 I kept the memory low so we can in future derive keys parallelly for multiple datasets and not run into memory bottlenecks and compensated for the security loss with increase in Time cost/Iterations.

As mentioned in my previous comment, A 3 second delay might be acceptable if a user only has a single dataset to unlock on login, but it quickly adds up with multiple datasets involved till we implement some kind of parallel key derivation.  Right now, just unlocking 3 datasets on login would take over 10s which is awfully long from a UX perspective.

We also have to keep in mind that FILES are also hashed with argon2 now as opposed to SHA512 like before and thus if a FILE Mode is used then the argon2 function have to be called 3 times (2 times for YubiKey) to derive the finale hash for a single dataset. 

Your valuable input is greatly appreciated.

**Comment by ashuio** [comment]
Hi @kiavash-at-work @kupiakos 

I have added multithreading support and bumped the iterations for argon2 to 4, I would really like to have your feedback on this.

**Comment by kiavash-at-work** [comment]
```rust
     let finalhash = crate::password::hash_argon2(&hashbuffer[..], crate::STATIC_SALT.as_bytes())
        .expect("Online File Hash Error");
```

I believe at one poit, the code was using a dynamic salt, but now [it](https://github.com/ashuio/shavee/blame/53f5dda1ac7d2792dc0e736966886372248d92ee/shavee-core/src/filehash.rs#L82) is back to static salt.

**Comment by ashuio** [comment]
> ```rust
>      let finalhash = crate::password::hash_argon2(&hashbuffer[..], crate::STATIC_SALT.as_bytes())
>         .expect("Online File Hash Error");
> ```
> 
> I believe at one poit, the code was using a dynamic salt, but now [it](https://github.com/ashuio/shavee/blame/53f5dda1ac7d2792dc0e736966886372248d92ee/shavee-core/src/filehash.rs#L82) is back to static salt.

It is actually using Both as you can see in line 21

```rust
config.hash_password_into(password, salt, &mut hash)?;
```

**Comment by ashuio** [comment]
Can you point me to any specific commit where it did?

**Comment by kiavash-at-work** [comment]
> Can you point me to any specific commit where it did?

https://github.com/ashuio/shavee/blame/53f5dda1ac7d2792dc0e736966886372248d92ee/shavee-core/src/filehash.rs#L82

**Comment by ashuio** [comment]
With the latest commit the need for these functions has been removed entirely and now should use dynamic salt
